//! Static compatibility corpus translated from grep, ripgrep, sed, and awk.
//!
//! These are deliberately data-driven: every vector is a compile-time constant,
//! the full audit reports all mismatches in one run, and known failures remain
//! executable instead of being deleted or weakened. See `docs/compatibility.md`.

use std::io::Write;
use std::process::{Command, Output, Stdio};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Family {
    Grep,
    Ripgrep,
    Sed,
    Awk,
}

#[derive(Clone, Copy)]
struct Case {
    id: &'static str,
    family: Family,
    origin: &'static str,
    program: &'static str,
    input: &'static [u8],
    expected_stdout: &'static [u8],
    expected_success: bool,
}

const fn ok(
    id: &'static str,
    family: Family,
    origin: &'static str,
    program: &'static str,
    input: &'static [u8],
    expected_stdout: &'static [u8],
) -> Case {
    Case {
        id,
        family,
        origin,
        program,
        input,
        expected_stdout,
        expected_success: true,
    }
}

const fn err(
    id: &'static str,
    family: Family,
    origin: &'static str,
    program: &'static str,
    input: &'static [u8],
) -> Case {
    Case {
        id,
        family,
        origin,
        program,
        input,
        expected_stdout: b"",
        expected_success: false,
    }
}

// Programs in this section use `x/.*\n?/ ... p`, the closest se spelling of
// grep's record-oriented output. Expected output follows grep, including its
// treatment of unterminated final records.
static GREP_CASES: &[Case] = &[
    ok(
        "grep.literal.middle",
        Family::Grep,
        "grep/basic",
        r"x/.*\n?/ g/needle/ p",
        b"hay\nneedle here\nstraw\n",
        b"needle here\n",
    ),
    ok(
        "grep.literal.start",
        Family::Grep,
        "grep/basic",
        r"x/.*\n?/ g/needle/ p",
        b"needle first\nnot it\n",
        b"needle first\n",
    ),
    ok(
        "grep.literal.end",
        Family::Grep,
        "grep/basic",
        r"x/.*\n?/ g/needle/ p",
        b"the needle\nneedle? no\n",
        b"the needle\nneedle? no\n",
    ),
    ok(
        "grep.literal.repeated_on_line",
        Family::Grep,
        "grep/basic",
        r"x/.*\n?/ g/aa/ p",
        b"aaaa\nbbbb\n",
        b"aaaa\n",
    ),
    ok(
        "grep.literal.metacharacters_fixed",
        Family::Grep,
        "grep -F",
        r"x/.*\n?/ g/\(\)/ p",
        b"blib\n()\nblab\n",
        b"()\n",
    ),
    ok(
        "grep.regex.dot",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a.c/ p",
        b"ac\nabc\na-c\n",
        b"abc\na-c\n",
    ),
    ok(
        "grep.regex.star_zero",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/ab*c/ p",
        b"ac\nabc\nabbbc\nadc\n",
        b"ac\nabc\nabbbc\n",
    ),
    ok(
        "grep.regex.plus",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/ab+c/ p",
        b"ac\nabc\nabbbc\n",
        b"abc\nabbbc\n",
    ),
    ok(
        "grep.regex.question",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/ab?c/ p",
        b"ac\nabc\nabbc\n",
        b"ac\nabc\n",
    ),
    ok(
        "grep.regex.alt",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/cat|dog/ p",
        b"cat\nfox\ndog\n",
        b"cat\ndog\n",
    ),
    ok(
        "grep.regex.group",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a(b|c)d/ p",
        b"abd\nacd\naed\n",
        b"abd\nacd\n",
    ),
    ok(
        "grep.regex.nested_groups",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a(((b)))c/ p",
        b"abc\nabbc\n",
        b"abc\n",
    ),
    ok(
        "grep.regex.interval_exact",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/ab{2}c/ p",
        b"abc\nabbc\nabbbc\n",
        b"abbc\n",
    ),
    ok(
        "grep.regex.interval_open",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/ab{2,}c/ p",
        b"abc\nabbc\nabbbbc\n",
        b"abbc\nabbbbc\n",
    ),
    ok(
        "grep.regex.interval_bounded",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/ab{2,3}c/ p",
        b"abc\nabbc\nabbbc\nabbbbc\n",
        b"abbc\nabbbc\n",
    ),
    ok(
        "grep.regex.class",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a[bc]d/ p",
        b"abd\nacd\naed\n",
        b"abd\nacd\n",
    ),
    ok(
        "grep.regex.negated_class",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a[^bc]d/ p",
        b"abd\nacd\naed\n",
        b"aed\n",
    ),
    ok(
        "grep.regex.range",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a[1-3]c/ p",
        b"a0c\na2c\na4c\n",
        b"a2c\n",
    ),
    ok(
        "grep.regex.digit_class",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/[[:digit:]]+/ p",
        b"abc\na019b\nxyz\n",
        b"a019b\n",
    ),
    ok(
        "grep.regex.lower_class",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/[[:lower:]]+/ p",
        b"ABC\nAabC\n123\n",
        b"AabC\n",
    ),
    ok(
        "grep.regex.upper_class",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/[[:upper:]]+/ p",
        b"abc\naBCd\n123\n",
        b"aBCd\n",
    ),
    ok(
        "grep.regex.xdigit_class",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/[[:xdigit:]]+/ p",
        b"xyz\np0f3Cq\n",
        b"p0f3Cq\n",
    ),
    ok(
        "grep.anchor.start",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/^abc/ p",
        b"abcdef\nxabc\nabc\n",
        b"abcdef\nabc\n",
    ),
    ok(
        "grep.anchor.end",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/abc$/ p",
        b"xabc\nabcx\nabc\n",
        b"xabc\nabc\n",
    ),
    ok(
        "grep.anchor.whole_line",
        Family::Grep,
        "grep/match-lines",
        r"x/.*\n?/ g/^abc$/ p",
        b"abc\nxabc\nabcx\n",
        b"abc\n",
    ),
    ok(
        "grep.anchor.empty_line",
        Family::Grep,
        "grep/empty-line",
        r"x/.*\n?/ g/^$/ p",
        b"a\n\nb\n",
        b"\n",
    ),
    ok(
        "grep.anchor.multiple_start",
        Family::Grep,
        "grep/multiple-begin-or-end-line",
        r"x/.*\n?/ g/^^a/ p",
        b"a\nba\n",
        b"a\n",
    ),
    ok(
        "grep.anchor.multiple_end",
        Family::Grep,
        "grep/multiple-begin-or-end-line",
        r"x/.*\n?/ g/a$$/ p",
        b"a\nab\n",
        b"a\n",
    ),
    ok(
        "grep.word_boundary",
        Family::Grep,
        "grep/word-delim-multibyte",
        r"x/.*\n?/ g/\bcat\b/ p",
        b"cat\nscat\ncat!\ncat_1\n",
        b"cat\ncat!\n",
    ),
    ok(
        "grep.nonword_boundary",
        Family::Grep,
        "grep/word-delim-multibyte",
        r"x/.*\n?/ g/\Bcat/ p",
        b"cat\nscat\n",
        b"scat\n",
    ),
    ok(
        "grep.escape_dot",
        Family::Grep,
        "grep/backslash-dot",
        r"x/.*\n?/ g/a\.c/ p",
        b"abc\na.c\na-c\n",
        b"a.c\n",
    ),
    ok(
        "grep.escape_star",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a\*c/ p",
        b"abc\na*c\n",
        b"a*c\n",
    ),
    ok(
        "grep.case_insensitive_ascii",
        Family::Grep,
        "grep/case-fold-char-class",
        r"x/.*\n?/ g/error/i p",
        b"error\nERROR\nError\nok\n",
        b"error\nERROR\nError\n",
    ),
    ok(
        "grep.case_sensitive_ascii",
        Family::Grep,
        "grep/basic",
        r"x/.*\n?/ g/error/ p",
        b"error\nERROR\n",
        b"error\n",
    ),
    ok(
        "grep.case_insensitive_unicode",
        Family::Grep,
        "grep/case-fold-char-type",
        r"x/.*\n?/ g/élan/i p",
        "ÉLAN\nélan\nother\n".as_bytes(),
        "ÉLAN\nélan\n".as_bytes(),
    ),
    ok(
        "grep.invert_literal",
        Family::Grep,
        "grep/status",
        r"x/.*\n?/ v/drop/ p",
        b"keep\ndrop\nalso keep\n",
        b"keep\nalso keep\n",
    ),
    ok(
        "grep.invert_regex",
        Family::Grep,
        "grep/status",
        r"x/.*\n?/ v/^[0-9]+$/ p",
        b"123\nabc\n4x\n",
        b"abc\n4x\n",
    ),
    ok(
        "grep.empty_pattern_all_lines",
        Family::Grep,
        "grep/empty-line",
        r"x/.*\n?/ g// p",
        b"abc\ndef\n",
        b"abc\ndef\n",
    ),
    ok(
        "grep.empty_pattern_blank_line",
        Family::Grep,
        "grep/empty-line",
        r"x/.*\n?/ g// p",
        b"\n",
        b"\n",
    ),
    ok(
        "grep.empty_input",
        Family::Grep,
        "grep/empty",
        r"x/.*\n?/ g/x/ p",
        b"",
        b"",
    ),
    ok(
        "grep.empty_input_empty_pattern",
        Family::Grep,
        "grep/empty-line",
        r"x/.*\n?/ g// p",
        b"",
        b"",
    ),
    ok(
        "grep.blank_lines_literal",
        Family::Grep,
        "grep/empty-line",
        r"x/.*\n?/ g/x/ p",
        b"\n\nx\n\n",
        b"x\n",
    ),
    ok(
        "grep.crlf_preserved",
        Family::Grep,
        "ripgrep/feature f416",
        r"x/.*\n?/ g/foo/ p",
        b"foo\r\nbar\r\n",
        b"foo\r\n",
    ),
    ok(
        "grep.nul_in_nonmatching_line",
        Family::Grep,
        "grep/null-byte",
        r"x/.*\n?/ g/hit/ p",
        b"a\0b\nhit\n",
        b"hit\n",
    ),
    ok(
        "grep.nul_in_matching_line",
        Family::Grep,
        "grep/null-byte",
        r"x/.*\n?/ g/hit/ p",
        b"a\0hit\nno\n",
        b"a\0hit\n",
    ),
    ok(
        "grep.unterminated_matching_line",
        Family::Grep,
        "grep/fillbuf-long-line",
        r"x/.*\n?/ g/hit/ p",
        b"no\nhit",
        b"hit",
    ),
    ok(
        "grep.unterminated_nonmatching_line",
        Family::Grep,
        "grep/fillbuf-long-line",
        r"x/.*\n?/ g/hit/ p",
        b"hit\nno",
        b"hit\n",
    ),
    ok(
        "grep.long_literal",
        Family::Grep,
        "grep/long-pattern-perf",
        r"x/.*\n?/ g/12345678901234567890123456789012/ p",
        b"x12345678901234567890123456789012y\nshort\n",
        b"x12345678901234567890123456789012y\n",
    ),
    ok(
        "grep.ipv4_ere",
        Family::Grep,
        "ripgrep/regression r93",
        r"x/.*\n?/ g/(\d{1,3}\.){3}\d{1,3}/ p",
        b"192.168.1.1\n9999\n",
        b"192.168.1.1\n",
    ),
    ok(
        "grep.alternation_empty_left",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/|ab/ p",
        b"z\nab\n",
        b"z\nab\n",
    ),
    ok(
        "grep.alternation_empty_right",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/ab|/ p",
        b"z\nab\n",
        b"z\nab\n",
    ),
    ok(
        "grep.optional_group",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a(b)?c/ p",
        b"ac\nabc\nabbc\n",
        b"ac\nabc\n",
    ),
    ok(
        "grep.greedy_within_line",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a.*c/ p",
        b"a1c2c\na\nc\n",
        b"a1c2c\n",
    ),
    ok(
        "grep.dot_does_not_cross_newline",
        Family::Grep,
        "grep/mb-dot-newline",
        r"x/.*\n?/ g/a.*b/ p",
        b"a\nb\nab\n",
        b"ab\n",
    ),
    ok(
        "grep.unicode_literal",
        Family::Grep,
        "grep/utf8-bracket",
        r"x/.*\n?/ g/λ/ p",
        "alpha\nλambda\n".as_bytes(),
        "λambda\n".as_bytes(),
    ),
    ok(
        "grep.unicode_class",
        Family::Grep,
        "grep/utf8-bracket",
        r"x/.*\n?/ g/[éλ]/ p",
        "plain\ncafé\nλ\n".as_bytes(),
        "café\nλ\n".as_bytes(),
    ),
    ok(
        "grep.unicode_property",
        Family::Grep,
        "ripgrep/unicode",
        r"x/.*\n?/ g/\p{Greek}+/ p",
        "latin\nαβγ\n".as_bytes(),
        "αβγ\n".as_bytes(),
    ),
    ok(
        "grep.horizontal_tab",
        Family::Grep,
        "grep/initial-tab",
        r"x/.*\n?/ g/^\t/ p",
        b"\tindented\nplain\n",
        b"\tindented\n",
    ),
    ok(
        "grep.vertical_tab_not_line_end",
        Family::Grep,
        "ripgrep/regression r128",
        r"x/.*\n?/ g/x/ p",
        b"a\x0b\nx\n",
        b"x\n",
    ),
    err(
        "grep.invalid_unclosed_class",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a[b/ p",
        b"abc\n",
    ),
    err(
        "grep.invalid_unclosed_group",
        Family::Grep,
        "grep/ere.tests",
        r"x/.*\n?/ g/a(b/ p",
        b"abc\n",
    ),
    err(
        "grep.invalid_reversed_range",
        Family::Grep,
        "grep/reversed-range-endpoints",
        r"x/.*\n?/ g/[z-a]/ p",
        b"z\n",
    ),
    ok(
        "grep.ere_backreference",
        Family::Grep,
        "grep/backref",
        r"x/.*\n?/ g/^(a)\1$/ p",
        b"aa\nab\n",
        b"aa\n",
    ),
];

static RIPGREP_CASES: &[Case] = &[
    ok(
        "rg.only_matching_words",
        Family::Ripgrep,
        "ripgrep/misc only_matching",
        r"x/[A-Z][a-z]+/ p",
        b"Doctor Watson met Sherlock Holmes.\n",
        b"Doctor\nWatson\nSherlock\nHolmes\n",
    ),
    ok(
        "rg.only_matching_alternation",
        Family::Ripgrep,
        "ripgrep/multiline only_matching",
        r"x/Watson|Sherlock/ p",
        b"Watson and Sherlock\n",
        b"Watson\nSherlock\n",
    ),
    ok(
        "rg.only_matching_nonoverlap",
        Family::Ripgrep,
        "ripgrep/search",
        r"x/aa/ p",
        b"aaaaa",
        b"aa\naa\n",
    ),
    ok(
        "rg.only_matching_empty_suppressed",
        Family::Ripgrep,
        "ripgrep/search empty matches",
        r"x/a*/ p",
        b"bbb",
        b"\n\n\n",
    ),
    ok(
        "rg.multiline_literal",
        Family::Ripgrep,
        "ripgrep/multiline overlap1",
        r"x/abc\ndef/ p",
        b"xxx\nabc\ndefxxxabc\ndefxxx\n",
        b"abc\ndef\nabc\ndef\n",
    ),
    ok(
        "rg.multiline_dot_default_off",
        Family::Ripgrep,
        "ripgrep/multiline dot_no_newline",
        r"x/foo.*bar/ p",
        b"foo\nbar\n",
        b"",
    ),
    ok(
        "rg.multiline_dotall",
        Family::Ripgrep,
        "ripgrep/multiline dot_all",
        r"x/foo.*bar/s p",
        b"foo\nmid\nbar\n",
        b"foo\nmid\nbar\n",
    ),
    ok(
        "rg.inline_dotall",
        Family::Ripgrep,
        "ripgrep/multiline dot_all",
        r"x/(?s)foo.*bar/ p",
        b"foo\nbar",
        b"foo\nbar\n",
    ),
    ok(
        "rg.inline_case_insensitive",
        Family::Ripgrep,
        "ripgrep/search",
        r"x/(?i)rust/ p",
        b"RUST rust RuSt",
        b"RUST\nrust\nRuSt\n",
    ),
    ok(
        "rg.unicode_word",
        Family::Ripgrep,
        "ripgrep/unicode",
        r"x/\w+/ p",
        "naïve café λ".as_bytes(),
        "naïve\ncafé\nλ\n".as_bytes(),
    ),
    ok(
        "rg.unicode_any_lazy",
        Family::Ripgrep,
        "ripgrep/multiline only_matching",
        r"x/Sherlock\p{Any}+?Holmes/ p",
        b"Sherlock\nthen Holmes",
        b"Sherlock\nthen Holmes\n",
    ),
    ok(
        "rg.named_capture_replace",
        Family::Ripgrep,
        "ripgrep/misc replace_named_groups",
        r"s/(?P<first>[A-Z][a-z]+) (?P<last>[A-Z][a-z]+)/$last, $first/g",
        b"Doctor Watson; Sherlock Holmes\n",
        b"Watson, Doctor; Holmes, Sherlock\n",
    ),
    ok(
        "rg.numbered_capture_replace",
        Family::Ripgrep,
        "ripgrep/misc replace_groups",
        r"s/([A-Z][a-z]+) ([A-Z][a-z]+)/$2, $1/g",
        b"Doctor Watson\n",
        b"Watson, Doctor\n",
    ),
    ok(
        "rg.whole_match_replace",
        Family::Ripgrep,
        "ripgrep/regression r1739",
        r"s/[a-z]+/<$0>/g",
        b"one two\n",
        b"<one> <two>\n",
    ),
    ok(
        "rg.replacement_dollar_literal",
        Family::Ripgrep,
        "ripgrep/replacement",
        r"s/x/$$/g",
        b"x x\n",
        b"$ $\n",
    ),
    ok(
        "rg.replacement_missing_group",
        Family::Ripgrep,
        "ripgrep/replacement",
        r"s/(a)?b/<$1>/g",
        b"ab b\n",
        b"<a> <>\n",
    ),
    ok(
        "rg.regex_ipv4",
        Family::Ripgrep,
        "ripgrep/regression r93",
        r"x/(\d{1,3}\.){3}\d{1,3}/ p",
        b"ip=192.168.1.1",
        b"192.168.1.1\n",
    ),
    ok(
        "rg.regex_dna",
        Family::Ripgrep,
        "ripgrep/regression r1319",
        r"x/TTGAGTCCAGGAG[ATCG]{2}C/ p",
        b"CCAGCTACTCGGGAGGCTGAGGCTGGAGGATCGCTTGAGTCCAGGAGTTC",
        b"TTGAGTCCAGGAGTTC\n",
    ),
    ok(
        "rg.bom_byte_offset",
        Family::Ripgrep,
        "ripgrep/regression r1638",
        r"x/x/ =",
        b"\xef\xbb\xbfx",
        b"3,4,1\n",
    ),
    ok(
        "rg.nul_literal_extract",
        Family::Ripgrep,
        "ripgrep/binary",
        r"x/\x00/ =",
        b"a\0b",
        b"1,2,1\n",
    ),
    ok(
        "rg.crlf_only_match",
        Family::Ripgrep,
        "ripgrep/feature f416",
        r"x/foo/ p",
        b"foo\r\nbar\r\n",
        b"foo\n",
    ),
    ok(
        "rg.line_anchor_crlf",
        Family::Ripgrep,
        "ripgrep/feature f416",
        r"x/.*\n?/ g/^foo\r?$/ p",
        b"foo\r\nfoobar\r\n",
        b"foo\r\n",
    ),
    ok(
        "rg.no_unicode_ascii_word",
        Family::Ripgrep,
        "ripgrep/regression r2574",
        r"x/(?-u:\w+)/ p",
        "café test".as_bytes(),
        b"caf\ntest\n",
    ),
    err(
        "rg.lookaround_default_rejected",
        Family::Ripgrep,
        "ripgrep/regex",
        r"x/foo(?=bar)/ p",
        b"foobar",
    ),
    err(
        "rg.backreference_default_rejected",
        Family::Ripgrep,
        "ripgrep/regex",
        r"x/(a)\1/ p",
        b"aa",
    ),
    ok(
        "rg.invalid_utf8_literal",
        Family::Ripgrep,
        "ripgrep/binary",
        r"x/hit/ p",
        b"\xffhit\xfe",
        b"hit\n",
    ),
    ok(
        "rg.multiline_newline_replace",
        Family::Ripgrep,
        "ripgrep/regression r1311",
        r"s/\n/?/g",
        b"hello\nworld\n",
        b"hello?world?",
    ),
    ok(
        "rg.empty_match_at_line",
        Family::Ripgrep,
        "ripgrep/regression r1765",
        r"x/x?/ p",
        b"\n",
        b"\n",
    ),
];

// sed normally executes its script once per pattern space (line). The `x` +
// group wrapper is therefore part of most translations below. Cases testing
// multiline modifiers or se's sed-like `t` use the whole input intentionally.
static SED_CASES: &[Case] = &[
    ok(
        "sed.substitute_first",
        Family::Sed,
        "sed/basic",
        r"x/.*\n?/ { s/foo/bar/ }",
        b"foo foo\n",
        b"bar foo\n",
    ),
    ok(
        "sed.substitute_first_each_line",
        Family::Sed,
        "sed/basic",
        r"x/.*\n?/ { s/foo/bar/ }",
        b"foo foo\nfoo foo\n",
        b"bar foo\nbar foo\n",
    ),
    ok(
        "sed.substitute_global",
        Family::Sed,
        "sed/subst-options",
        r"x/.*\n?/ { s/foo/bar/g }",
        b"foo foo foo\n",
        b"bar bar bar\n",
    ),
    ok(
        "sed.no_match_passthrough",
        Family::Sed,
        "sed/basic",
        r"x/.*\n?/ { s/zzz/x/ }",
        b"hello\n",
        b"hello\n",
    ),
    ok(
        "sed.case_insensitive_lower_flag",
        Family::Sed,
        "sed/subst-options",
        r"x/.*\n?/ { s/foo/x/gi }",
        b"FOO Foo foo\n",
        b"x x x\n",
    ),
    ok(
        "sed.case_insensitive_upper_flag",
        Family::Sed,
        "sed/subst-options",
        r"x/.*\n?/ { s/foo/x/gI }",
        b"FOO Foo foo\n",
        b"x x x\n",
    ),
    ok(
        "sed.alternate_hash_delimiter",
        Family::Sed,
        "sed/compile-tests",
        r"x/.*\n?/ { s#usr/local#opt/homebrew# }",
        b"/usr/local/bin\n",
        b"/opt/homebrew/bin\n",
    ),
    ok(
        "sed.alternate_pipe_delimiter",
        Family::Sed,
        "sed/compile-tests",
        r"x/.*\n?/ { s|a/b|c/d| }",
        b"a/b\n",
        b"c/d\n",
    ),
    ok(
        "sed.escaped_delimiter_pattern",
        Family::Sed,
        "sed/mb-match-slash",
        r"x/.*\n?/ { s/a\/b/x/ }",
        b"a/b\n",
        b"x\n",
    ),
    ok(
        "sed.escaped_delimiter_replacement",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/x/a\/b/ }",
        b"x\n",
        b"a/b\n",
    ),
    ok(
        "sed.capture_one",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(1)(2)(3)(4)(5)(6)(7)(8)(9)/\1/ }",
        b"123456789\n",
        b"1\n",
    ),
    ok(
        "sed.capture_two",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(1)(2)(3)(4)(5)(6)(7)(8)(9)/\2/ }",
        b"123456789\n",
        b"2\n",
    ),
    ok(
        "sed.capture_three",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(1)(2)(3)(4)(5)(6)(7)(8)(9)/\3/ }",
        b"123456789\n",
        b"3\n",
    ),
    ok(
        "sed.capture_four",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(1)(2)(3)(4)(5)(6)(7)(8)(9)/\4/ }",
        b"123456789\n",
        b"4\n",
    ),
    ok(
        "sed.capture_five",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(1)(2)(3)(4)(5)(6)(7)(8)(9)/\5/ }",
        b"123456789\n",
        b"5\n",
    ),
    ok(
        "sed.capture_six",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(1)(2)(3)(4)(5)(6)(7)(8)(9)/\6/ }",
        b"123456789\n",
        b"6\n",
    ),
    ok(
        "sed.capture_seven",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(1)(2)(3)(4)(5)(6)(7)(8)(9)/\7/ }",
        b"123456789\n",
        b"7\n",
    ),
    ok(
        "sed.capture_eight",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(1)(2)(3)(4)(5)(6)(7)(8)(9)/\8/ }",
        b"123456789\n",
        b"8\n",
    ),
    ok(
        "sed.capture_nine",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(1)(2)(3)(4)(5)(6)(7)(8)(9)/\9/ }",
        b"123456789\n",
        b"9\n",
    ),
    ok(
        "sed.capture_reorder",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/([a-z]+), ([a-z]+)/\2 \1/ }",
        b"doe, jane\n",
        b"jane doe\n",
    ),
    ok(
        "sed.capture_optional_present",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(a)?b/[\1]/ }",
        b"ab\n",
        b"[a]\n",
    ),
    ok(
        "sed.capture_optional_absent",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(a)?b/[\1]/ }",
        b"b\n",
        b"[]\n",
    ),
    ok(
        "sed.whole_match_ampersand",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/[0-9]+/[&]/ }",
        b"id=42\n",
        b"id=[42]\n",
    ),
    ok(
        "sed.whole_match_backslash_zero",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(.)(.)/\0/ }",
        b"ab\n",
        b"ab\n",
    ),
    ok(
        "sed.escaped_ampersand_literal",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/x/\&/ }",
        b"x\n",
        b"&\n",
    ),
    ok(
        "sed.unknown_replacement_escape",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/a/\Q/ }",
        b"a\n",
        b"Q\n",
    ),
    ok(
        "sed.replacement_newline",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/,/\n/g }",
        b"a,b,c\n",
        b"a\nb\nc\n",
    ),
    ok(
        "sed.replacement_tab",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/,/\t/g }",
        b"a,b\n",
        b"a\tb\n",
    ),
    ok(
        "sed.replacement_carriage_return",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/,/\r/g }",
        b"a,b\n",
        b"a\rb\n",
    ),
    ok(
        "sed.replacement_backslash",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/x/\\/ }",
        b"x\n",
        b"\\\n",
    ),
    ok(
        "sed.literal_dollar",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/x/$$/ }",
        b"x\n",
        b"$$\n",
    ),
    ok(
        "sed.anchor_start_each_line",
        Family::Sed,
        "sed/subst-options",
        r"x/.*\n?/ { s/^/X/ }",
        b"foo\nbar\n",
        b"Xfoo\nXbar\n",
    ),
    ok(
        "sed.anchor_end_each_line",
        Family::Sed,
        "sed/subst-options",
        r"x/.*\n?/ { s/$/X/ }",
        b"foo\nbar\n",
        b"fooX\nbarX\n",
    ),
    ok(
        "sed.dot_each_line",
        Family::Sed,
        "sed/basic",
        r"x/.*\n?/ { s/./X/g }",
        b"ab\ncd\n",
        b"XX\nXX\n",
    ),
    ok(
        "sed.class_global",
        Family::Sed,
        "sed/posix-char-class",
        r"x/.*\n?/ { s/[[:digit:]]/#/g }",
        b"a1b22\n",
        b"a#b##\n",
    ),
    ok(
        "sed.alternation",
        Family::Sed,
        "sed/posix-mode-ERE",
        r"x/.*\n?/ { s/cat|dog/pet/g }",
        b"cat dog fox\n",
        b"pet pet fox\n",
    ),
    ok(
        "sed.unterminated_final_line_preserved",
        Family::Sed,
        "sed/stdin",
        r"x/.*\n?/ { s/foo/bar/ }",
        b"foo",
        b"bar",
    ),
    ok(
        "sed.empty_input",
        Family::Sed,
        "sed/stdin",
        r"x/.*\n?/ { s/foo/bar/ }",
        b"",
        b"",
    ),
    ok(
        "sed.nul_input",
        Family::Sed,
        "sed/nulldata",
        r"x/.*\n?/ { s/foo/bar/g }",
        b"foo\0foo\n",
        b"bar\0bar\n",
    ),
    ok(
        "sed.multiline_dotall",
        Family::Sed,
        "sed/subst-options",
        r"s/foo.*bar/X/s",
        b"foo\nmid\nbar\n",
        b"X\n",
    ),
    ok(
        "sed.multiline_anchor_m",
        Family::Sed,
        "sed/subst-options",
        r"s/^./X/gm",
        b"foo\nbar\n",
        b"Xoo\nXar\n",
    ),
    ok(
        "sed.global_zero_width_start",
        Family::Sed,
        "sed/subst-options",
        r"s/^/X/gm",
        b"a\nb\n",
        b"Xa\nXb\n",
    ),
    ok(
        "sed.global_zero_width_end",
        Family::Sed,
        "sed/subst-options",
        r"s/$/X/gm",
        b"a\nb\n",
        b"aX\nbX\n",
    ),
    ok(
        "sed.numeric_second_match",
        Family::Sed,
        "sed/subst-options",
        r"x/.*\n?/ { s/b/x/2 }",
        b"bbbb\n",
        b"bxbb\n",
    ),
    ok(
        "sed.numeric_ninth_match",
        Family::Sed,
        "sed/subst-options",
        r"x/.*\n?/ { s/b/x/9 }",
        b"bbbbbbbbbb\n",
        b"bbbbbbbbxb\n",
    ),
    ok(
        "sed.uppercase_all_replacement",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(.)(.)(.)/\U\1\2\3/ }",
        b"abCde\n",
        b"ABCde\n",
    ),
    ok(
        "sed.uppercase_next_replacement",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(.)(.)(.)/\u\1\2\3/ }",
        b"abCde\n",
        b"AbCde\n",
    ),
    ok(
        "sed.lowercase_all_replacement",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(.)(.)(.)/\L\1\2\3/ }",
        b"AbCde\n",
        b"abcde\n",
    ),
    ok(
        "sed.lowercase_next_replacement",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(.)(.)(.)/\l\1\2\3/ }",
        b"AbCde\n",
        b"abCde\n",
    ),
    ok(
        "sed.case_conversion_end",
        Family::Sed,
        "sed/subst-replacement",
        r"x/.*\n?/ { s/(.)(.)(.)/\U\1\E\2\3/ }",
        b"abCde\n",
        b"AbCde\n",
    ),
    ok(
        "sed.address_match",
        Family::Sed,
        "sed/address",
        r"/foo/ { s/foo/bar/g }",
        b"foo foo\nother\n",
        b"bar bar\nother\n",
    ),
    ok(
        "sed.address_nonmatch",
        Family::Sed,
        "sed/address",
        r"/foo/ { s/x/y/g }",
        b"x\nfoo x\n",
        b"x\nfoo y\n",
    ),
    ok(
        "sed.chained_substitution",
        Family::Sed,
        "sed/execute-tests",
        r"x/.*\n?/ { s/a/b/ s/b/c/ }",
        b"a\n",
        b"c\n",
    ),
    ok(
        "sed.branch_after_success",
        Family::Sed,
        "sed/execute-tests",
        r"s/a/b/ t { s/x/y/ }",
        b"ax\n",
        b"by\n",
    ),
    ok(
        "sed.branch_after_failure",
        Family::Sed,
        "sed/execute-tests",
        r"s/a/b/ t { s/x/y/ }",
        b"xx\n",
        b"xx\n",
    ),
    err(
        "sed.invalid_regex",
        Family::Sed,
        "sed/regex-errors",
        r"s/[/x/",
        b"a\n",
    ),
];

static AWK_CASES: &[Case] = &[
    ok(
        "awk.print_record",
        Family::Awk,
        "awk language",
        r"x/.*\n/ @{ print }",
        b"alpha beta\n",
        b"alpha beta\n",
    ),
    ok(
        "awk.print_field_zero",
        Family::Awk,
        "awk language",
        r"x/.*\n/ @{ print $0 }",
        b"alpha beta\n",
        b"alpha beta\n",
    ),
    ok(
        "awk.fields_basic",
        Family::Awk,
        "gawk field tests",
        r"x/.*\n/ @{ print $1, $2, $3 }",
        b"a b c\n",
        b"a b c\n",
    ),
    ok(
        "awk.fields_whitespace_runs",
        Family::Awk,
        "gawk field tests",
        r"x/.*\n/ @{ print NF, $1, $3 }",
        b"  a\t b   c  \n",
        b"3 a c\n",
    ),
    ok(
        "awk.missing_field_empty",
        Family::Awk,
        "gawk field tests",
        r#"x/.*\n/ @{ print "[" $4 "]" }"#,
        b"a b\n",
        b"[]\n",
    ),
    ok(
        "awk.dynamic_field_nf",
        Family::Awk,
        "gawk field tests",
        r"x/.*\n/ @{ print $NF }",
        b"a b c\n",
        b"c\n",
    ),
    ok(
        "awk.dynamic_field_expression",
        Family::Awk,
        "gawk field tests",
        r"x/.*\n/ @{ i=2; print $(i+1) }",
        b"a b c d\n",
        b"c\n",
    ),
    ok(
        "awk.nr_increments",
        Family::Awk,
        "gawk field tests",
        r"x/.*\n/ @{ print NR, $1 }",
        b"a\nb\nc\n",
        b"1 a\n2 b\n3 c\n",
    ),
    ok(
        "awk.nf_per_record",
        Family::Awk,
        "gawk field tests",
        r"x/.*\n/ @{ print NF }",
        b"a b c\nd e\n\n",
        b"3\n2\n0\n",
    ),
    ok(
        "awk.fnr_single_input",
        Family::Awk,
        "awk special variables",
        r"x/.*\n/ @{ print FNR }",
        b"a\nb\n",
        b"1\n2\n",
    ),
    ok(
        "awk.begin_before_records",
        Family::Awk,
        "awk BEGIN",
        r#"x/.*\n/ @{ BEGIN { print "start" } print $1 }"#,
        b"a\nb\n",
        b"start\na\nb\n",
    ),
    ok(
        "awk.end_after_records",
        Family::Awk,
        "awk END",
        r#"x/.*\n/ @{ n++ END { print "count=" n } }"#,
        b"a\nb\n",
        b"count=2\n",
    ),
    ok(
        "awk.begin_and_end_empty_input",
        Family::Awk,
        "awk BEGIN/END",
        r#"x/.*\n/ @{ BEGIN { print "B" } END { print "E" } }"#,
        b"",
        b"B\nE\n",
    ),
    ok(
        "awk.unterminated_final_record",
        Family::Awk,
        "gawk/nonl",
        r"x/.*\n?/ @{ print NR, $0 }",
        b"tail",
        b"1 tail\n",
    ),
    ok(
        "awk.fs_colon",
        Family::Awk,
        "gawk field tests",
        r#"x/.*\n/ @{ BEGIN { FS=":" } print $2 }"#,
        b"a:b:c\n",
        b"b\n",
    ),
    ok(
        "awk.fs_keeps_empty_fields",
        Family::Awk,
        "gawk field tests",
        r#"x/.*\n/ @{ BEGIN { FS=":" } print NF, "[" $2 "]", "[" $4 "]" }"#,
        b"a::c:\n",
        b"4 [] []\n",
    ),
    ok(
        "awk.fs_empty_splits_characters",
        Family::Awk,
        "gawk field tests",
        r#"x/.*\n/ @{ BEGIN { FS="" } print NF, $1, $3 }"#,
        b"abc\n",
        b"3 a c\n",
    ),
    ok(
        "awk.fs_empty_unicode_characters",
        Family::Awk,
        "gawk multibyte",
        r#"x/.*\n/ @{ BEGIN { FS="" } print NF, $2 }"#,
        "aλc\n".as_bytes(),
        "3 λ\n".as_bytes(),
    ),
    ok(
        "awk.fs_multichar_regex",
        Family::Awk,
        "gawk field tests",
        r#"x/.*\n/ @{ BEGIN { FS="[,:]+" } print NF, $1, $2, $3 }"#,
        b"a,,b:c\n",
        b"3 a b c\n",
    ),
    ok(
        "awk.ofs",
        Family::Awk,
        "awk special variables",
        r#"x/.*\n/ @{ BEGIN { OFS="|" } print $1, $2 }"#,
        b"a b\n",
        b"a|b\n",
    ),
    ok(
        "awk.ors",
        Family::Awk,
        "awk special variables",
        r#"x/.*\n/ @{ BEGIN { ORS=";" } print $1 }"#,
        b"a\nb\n",
        b"a;b;",
    ),
    ok(
        "awk.assign_field",
        Family::Awk,
        "gawk field tests",
        r#"x/.*\n/ @{ BEGIN { OFS=":" } $2="X"; print $0 }"#,
        b"a b c\n",
        b"a:X:c\n",
    ),
    ok(
        "awk.assign_field_zero_resplits",
        Family::Awk,
        "gawk field tests",
        r#"x/.*\n/ @{ $0="x y"; print NF, $2 }"#,
        b"a:b:c\n",
        b"2 y\n",
    ),
    ok(
        "awk.extend_field",
        Family::Awk,
        "gawk field tests",
        r#"x/.*\n/ @{ BEGIN { OFS=":" } $4="d"; print NF, $0 }"#,
        b"a b\n",
        b"4:a:b::d\n",
    ),
    ok(
        "awk.assign_nf_shrink",
        Family::Awk,
        "gawk/nfset",
        r"x/.*\n/ @{ NF=2; print NF, $0 }",
        b"a b c d\n",
        b"2 a b\n",
    ),
    ok(
        "awk.assign_nf_grow",
        Family::Awk,
        "gawk/nfset",
        r#"x/.*\n/ @{ BEGIN { OFS=":" } NF=4; print NF, $0 }"#,
        b"a b\n",
        b"4:a:b::\n",
    ),
    ok(
        "awk.addition",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ print $1 + $2 }",
        b"10 32\n",
        b"42\n",
    ),
    ok(
        "awk.subtraction",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ print $1 - $2 }",
        b"10 3\n",
        b"7\n",
    ),
    ok(
        "awk.multiplication",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ print $1 * $2 }",
        b"6 7\n",
        b"42\n",
    ),
    ok(
        "awk.division",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ print $1 / $2 }",
        b"9 2\n",
        b"4.5\n",
    ),
    ok(
        "awk.modulo",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ print $1 % $2 }",
        b"17 5\n",
        b"2\n",
    ),
    ok(
        "awk.power",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ print 2 ^ 10 }",
        b"x\n",
        b"1024\n",
    ),
    ok(
        "awk.power_right_associative",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ print 2 ^ 3 ^ 2 }",
        b"x\n",
        b"512\n",
    ),
    ok(
        "awk.arithmetic_precedence",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ print 2 + 3 * 4, (2 + 3) * 4 }",
        b"x\n",
        b"14 20\n",
    ),
    ok(
        "awk.unary_minus_power",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ print -2 ^ 2, (-2) ^ 2 }",
        b"x\n",
        b"-4 4\n",
    ),
    ok(
        "awk.compound_assignments",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ x=10; x+=5; x-=3; x*=2; x/=4; x%=4; x^=2; print x }",
        b"x\n",
        b"4\n",
    ),
    ok(
        "awk.pre_increment",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ x=1; print ++x, x }",
        b"x\n",
        b"2 2\n",
    ),
    ok(
        "awk.post_increment",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ x=1; print x++, x }",
        b"x\n",
        b"1 2\n",
    ),
    ok(
        "awk.pre_decrement",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ x=1; print --x, x }",
        b"x\n",
        b"0 0\n",
    ),
    ok(
        "awk.post_decrement",
        Family::Awk,
        "awk arithmetic",
        r"x/.*\n/ @{ x=1; print x--, x }",
        b"x\n",
        b"1 0\n",
    ),
    ok(
        "awk.numeric_prefix",
        Family::Awk,
        "gawk strtod",
        r"x/.*\n/ @{ print $1 + 1 }",
        b"12.5xyz\n",
        b"13.5\n",
    ),
    ok(
        "awk.scientific_number",
        Family::Awk,
        "gawk strtod",
        r"x/.*\n/ @{ print $1 + 1 }",
        b"1.5e2x\n",
        b"151\n",
    ),
    ok(
        "awk.string_concat",
        Family::Awk,
        "awk expressions",
        r#"x/.*\n/ @{ print $1 "=" $2 }"#,
        b"key value\n",
        b"key=value\n",
    ),
    ok(
        "awk.concat_precedence",
        Family::Awk,
        "awk expressions",
        r#"x/.*\n/ @{ print "x" 1+2 }"#,
        b"x\n",
        b"x3\n",
    ),
    ok(
        "awk.numeric_comparisons",
        Family::Awk,
        "gawk compare",
        r"x/.*\n/ @{ print (2<10), (2<=2), (3>2), (3>=4), (2==2), (2!=3) }",
        b"x\n",
        b"1 1 1 0 1 1\n",
    ),
    ok(
        "awk.numeric_string_comparison",
        Family::Awk,
        "gawk compare",
        r#"x/.*\n/ @{ print ("02" == 2), ("10" < "2") }"#,
        b"x\n",
        b"0 1\n",
    ),
    ok(
        "awk.nonnumeric_string_comparison",
        Family::Awk,
        "gawk compare",
        r#"x/.*\n/ @{ print ("10x" < "2x"), ("a" == "a") }"#,
        b"x\n",
        b"1 1\n",
    ),
    ok(
        "awk.logical_short_circuit_and",
        Family::Awk,
        "awk expressions",
        r"x/.*\n/ @{ x=0; print (0 && ++x), x }",
        b"x\n",
        b"0 0\n",
    ),
    ok(
        "awk.logical_short_circuit_or",
        Family::Awk,
        "awk expressions",
        r"x/.*\n/ @{ x=0; print (1 || ++x), x }",
        b"x\n",
        b"1 0\n",
    ),
    ok(
        "awk.truth_zero_string",
        Family::Awk,
        "awk truth",
        r#"x/.*\n/ @{ if ($1) print "T"; else print "F" }"#,
        b"0\n",
        b"F\n",
    ),
    ok(
        "awk.truth_nonnumeric_string",
        Family::Awk,
        "awk truth",
        r#"x/.*\n/ @{ if ($1) print "T"; else print "F" }"#,
        b"hello\n",
        b"T\n",
    ),
    ok(
        "awk.ternary",
        Family::Awk,
        "awk expressions",
        r#"x/.*\n/ @{ print ($1 > 5 ? "big" : "small") }"#,
        b"8\n2\n",
        b"big\nsmall\n",
    ),
    ok(
        "awk.if_else",
        Family::Awk,
        "awk control",
        r#"x/.*\n/ @{ if ($1%2) print "odd"; else print "even" }"#,
        b"3\n4\n",
        b"odd\neven\n",
    ),
    ok(
        "awk.while_loop",
        Family::Awk,
        "awk control",
        r"x/.*\n/ @{ i=0; while (i<3) { print i; i++ } }",
        b"x\n",
        b"0\n1\n2\n",
    ),
    ok(
        "awk.while_break",
        Family::Awk,
        "awk control",
        r"x/.*\n/ @{ i=0; while (1) { if (i==2) break; print i; i++ } }",
        b"x\n",
        b"0\n1\n",
    ),
    ok(
        "awk.while_continue",
        Family::Awk,
        "awk control",
        r"x/.*\n/ @{ i=0; while (i<4) { i++; if (i==2) continue; print i } }",
        b"x\n",
        b"1\n3\n4\n",
    ),
    ok(
        "awk.for_loop",
        Family::Awk,
        "awk control",
        r"x/.*\n/ @{ for (i=0; i<3; i++) print i }",
        b"x\n",
        b"0\n1\n2\n",
    ),
    ok(
        "awk.for_empty_parts",
        Family::Awk,
        "awk control",
        r"x/.*\n/ @{ i=0; for (;;) { if (i==2) break; print i; i++ } }",
        b"x\n",
        b"0\n1\n",
    ),
    ok(
        "awk.next_record",
        Family::Awk,
        "awk control",
        r#"x/.*\n/ @{ if ($1=="skip") next; print $1 }"#,
        b"keep\nskip\nafter\n",
        b"keep\nafter\n",
    ),
    ok(
        "awk.array_count",
        Family::Awk,
        "gawk arrays",
        r#"x/.*\n/ @{ c[$1]++ END { print c["a"], c["b"] } }"#,
        b"a\nb\na\n",
        b"2 1\n",
    ),
    ok(
        "awk.array_membership",
        Family::Awk,
        "gawk arrays",
        r#"x/.*\n/ @{ a["x"]=1; print ("x" in a), ("y" in a) }"#,
        b"z\n",
        b"1 0\n",
    ),
    ok(
        "awk.array_delete_element",
        Family::Awk,
        "gawk arrays",
        r#"x/.*\n/ @{ a["x"]=1; delete a["x"]; print ("x" in a) }"#,
        b"z\n",
        b"0\n",
    ),
    ok(
        "awk.array_delete_all",
        Family::Awk,
        "gawk arrays",
        r#"x/.*\n/ @{ a["x"]=1; a["y"]=1; delete a; n=0; for (k in a) n++; print n }"#,
        b"z\n",
        b"0\n",
    ),
    ok(
        "awk.array_multi_index",
        Family::Awk,
        "gawk arrays",
        r#"x/.*\n/ @{ a[1,2]="ok"; print a[1,2] }"#,
        b"z\n",
        b"ok\n",
    ),
    ok(
        "awk.array_custom_subsep",
        Family::Awk,
        "gawk arrays",
        r#"x/.*\n/ @{ SUBSEP=":"; a[1,2]="ok"; print a[1,2] }"#,
        b"z\n",
        b"ok\n",
    ),
    ok(
        "awk.for_in_count",
        Family::Awk,
        "gawk arrays",
        r"x/.*\n/ @{ a[$1]=1 END { n=0; for (k in a) n++; print n } }",
        b"x\ny\nx\n",
        b"2\n",
    ),
    ok(
        "awk.split_default",
        Family::Awk,
        "gawk split",
        r"x/.*\n/ @{ n=split($0,a); print n, a[1], a[n] }",
        b"a b c\n",
        b"3 a c\n",
    ),
    ok(
        "awk.split_separator",
        Family::Awk,
        "gawk split",
        r#"x/.*\n/ @{ n=split($0,a,","); print n, a[2] }"#,
        b"a,b,c\n",
        b"3 b\n",
    ),
    ok(
        "awk.split_replaces_array",
        Family::Awk,
        "gawk split",
        r#"x/.*\n/ @{ a[9]="old"; split("x:y",a,":"); print (9 in a), a[2] }"#,
        b"z\n",
        b"0 y\n",
    ),
    ok(
        "awk.length_record",
        Family::Awk,
        "gawk string functions",
        r"x/.*\n/ @{ print length }",
        b"abc de\n",
        b"6\n",
    ),
    ok(
        "awk.length_argument",
        Family::Awk,
        "gawk string functions",
        r"x/.*\n/ @{ print length($1) }",
        b"abcdef\n",
        b"6\n",
    ),
    ok(
        "awk.length_unicode",
        Family::Awk,
        "gawk multibyte",
        r"x/.*\n/ @{ print length($1) }",
        "aλé\n".as_bytes(),
        b"3\n",
    ),
    ok(
        "awk.substr_two_args",
        Family::Awk,
        "gawk string functions",
        r"x/.*\n/ @{ print substr($1,3) }",
        b"abcdef\n",
        b"cdef\n",
    ),
    ok(
        "awk.substr_three_args",
        Family::Awk,
        "gawk string functions",
        r"x/.*\n/ @{ print substr($1,2,3) }",
        b"abcdef\n",
        b"bcd\n",
    ),
    ok(
        "awk.substr_unicode",
        Family::Awk,
        "gawk multibyte",
        r"x/.*\n/ @{ print substr($1,2,2) }",
        "aλéc\n".as_bytes(),
        "λé\n".as_bytes(),
    ),
    ok(
        "awk.index_found",
        Family::Awk,
        "gawk string functions",
        r#"x/.*\n/ @{ print index($1,"cd") }"#,
        b"abcdef\n",
        b"3\n",
    ),
    ok(
        "awk.index_not_found",
        Family::Awk,
        "gawk string functions",
        r#"x/.*\n/ @{ print index($1,"zz") }"#,
        b"abcdef\n",
        b"0\n",
    ),
    ok(
        "awk.index_unicode",
        Family::Awk,
        "gawk multibyte",
        r#"x/.*\n/ @{ print index($1,"é") }"#,
        "aλéc\n".as_bytes(),
        b"3\n",
    ),
    ok(
        "awk.tolower",
        Family::Awk,
        "gawk string functions",
        r"x/.*\n/ @{ print tolower($1) }",
        b"AbC\n",
        b"abc\n",
    ),
    ok(
        "awk.toupper",
        Family::Awk,
        "gawk string functions",
        r"x/.*\n/ @{ print toupper($1) }",
        b"AbC\n",
        b"ABC\n",
    ),
    ok(
        "awk.sqrt_int_log",
        Family::Awk,
        "gawk math",
        r"x/.*\n/ @{ print sqrt(144), int(-3.9), log(1) }",
        b"x\n",
        b"12 -3 0\n",
    ),
    ok(
        "awk.sin_cos",
        Family::Awk,
        "gawk math",
        r#"x/.*\n/ @{ printf "%.0f %.0f\n", sin(0), cos(0) }"#,
        b"x\n",
        b"0 1\n",
    ),
    ok(
        "awk.atan2",
        Family::Awk,
        "gawk math",
        r#"x/.*\n/ @{ printf "%.3f\n", atan2(0,-1) }"#,
        b"x\n",
        b"3.142\n",
    ),
    ok(
        "awk.exp",
        Family::Awk,
        "gawk math",
        r#"x/.*\n/ @{ printf "%.3f\n", exp(1) }"#,
        b"x\n",
        b"2.718\n",
    ),
    ok(
        "awk.srand_return_previous",
        Family::Awk,
        "gawk rand",
        r"x/.*\n/ @{ BEGIN { srand(7); print srand(8) } }",
        b"x\n",
        b"7\n",
    ),
    ok(
        "awk.rand_range",
        Family::Awk,
        "gawk rand",
        r"x/.*\n/ @{ BEGIN { srand(1); r=rand(); print (r>=0 && r<1) } }",
        b"x\n",
        b"1\n",
    ),
    ok(
        "awk.sprintf",
        Family::Awk,
        "gawk sprintf",
        r#"x/.*\n/ @{ print sprintf("%04d-%s", 7, "x") }"#,
        b"z\n",
        b"0007-x\n",
    ),
    ok(
        "awk.printf_integer_flags",
        Family::Awk,
        "gawk printf",
        r#"x/.*\n/ @{ printf "%+d|% d|%05d|%-5d\n", 7, 7, 7, 7 }"#,
        b"z\n",
        b"+7| 7|00007|7    \n",
    ),
    ok(
        "awk.printf_radix",
        Family::Awk,
        "gawk printf",
        r#"x/.*\n/ @{ printf "%o|%#x|%#X\n", 10, 10, 10 }"#,
        b"z\n",
        b"12|0xa|0XA\n",
    ),
    ok(
        "awk.printf_float",
        Family::Awk,
        "gawk printf",
        r#"x/.*\n/ @{ printf "%.2f|%.2e|%.3g\n", 3.14159, 12.5, 1234 }"#,
        b"z\n",
        b"3.14|1.25e+01|1.23e+03\n",
    ),
    ok(
        "awk.printf_string_precision",
        Family::Awk,
        "gawk printf",
        r#"x/.*\n/ @{ printf "%5.3s\n", "abcdef" }"#,
        b"z\n",
        b"  abc\n",
    ),
    ok(
        "awk.printf_char_number",
        Family::Awk,
        "gawk printf",
        r#"x/.*\n/ @{ printf "%c\n", 65 }"#,
        b"z\n",
        b"A\n",
    ),
    ok(
        "awk.printf_percent",
        Family::Awk,
        "gawk printf",
        r#"x/.*\n/ @{ printf "100%%\n" }"#,
        b"z\n",
        b"100%\n",
    ),
    ok(
        "awk.printf_dynamic_width",
        Family::Awk,
        "gawk printf",
        r#"x/.*\n/ @{ printf "%*s\n", 4, "x" }"#,
        b"z\n",
        b"   x\n",
    ),
    ok(
        "awk.convfmt",
        Family::Awk,
        "gawk convfmt",
        r#"x/.*\n/ @{ BEGIN { CONVFMT="%.2f"; x=1/3; print x "" } }"#,
        b"z\n",
        b"0.33\n",
    ),
    ok(
        "awk.ofmt",
        Family::Awk,
        "gawk ofmt",
        r#"x/.*\n/ @{ BEGIN { OFMT="%.2f"; print 1/3 } }"#,
        b"z\n",
        b"0.33\n",
    ),
    ok(
        "awk.large_number_default_format",
        Family::Awk,
        "gawk numeric formatting",
        r"x/.*\n/ @{ print 1e20 }",
        b"z\n",
        b"1e+20\n",
    ),
    ok(
        "awk.regex_match_operator",
        Family::Awk,
        "awk regex",
        r#"x/.*\n/ @{ if ($0 ~ "foo") print $0 }"#,
        b"foo\nbar\n",
        b"foo\n",
    ),
    ok(
        "awk.gsub_builtin",
        Family::Awk,
        "gawk gsub",
        r#"x/.*\n/ @{ gsub("a","x"); print }"#,
        b"banana\n",
        b"bxnxnx\n",
    ),
    ok(
        "awk.user_function",
        Family::Awk,
        "gawk functions",
        r"x/.*\n/ @{ function twice(x) { return x*2 } print twice($1) }",
        b"21\n",
        b"42\n",
    ),
    err(
        "awk.division_by_zero_error",
        Family::Awk,
        "gawk arithmetic",
        r"x/.*\n/ @{ print 1/0 }",
        b"z\n",
    ),
    err(
        "awk.negative_field_error",
        Family::Awk,
        "gawk field tests",
        r"x/.*\n/ @{ print $-1 }",
        b"z\n",
    ),
    err(
        "awk.wrong_builtin_arity_error",
        Family::Awk,
        "gawk builtins",
        r"x/.*\n/ @{ print sqrt(1,2) }",
        b"z\n",
    ),
    err(
        "awk.parse_error",
        Family::Awk,
        "gawk syntax",
        r"x/.*\n/ @{ if ( }",
        b"z\n",
    ),
];

#[derive(Clone, Copy)]
struct KnownFailure {
    id: &'static str,
    actual_stdout: &'static [u8],
    actual_success: bool,
    stderr_contains: &'static str,
}

// Filled only after a full audit. Each entry pins se's current wrong behavior,
// while the corresponding Case above continues to pin the desired behavior.
static KNOWN_FAILURES: &[KnownFailure] = &[
    KnownFailure {
        id: "grep.unterminated_matching_line",
        actual_stdout: b"hit\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "grep.ere_backreference",
        actual_stdout: b"",
        actual_success: false,
        stderr_contains: "Invalid regex",
    },
    KnownFailure {
        id: "sed.literal_dollar",
        actual_stdout: b"$\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "sed.uppercase_all_replacement",
        actual_stdout: b"UabCde\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "sed.uppercase_next_replacement",
        actual_stdout: b"uabCde\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "sed.lowercase_all_replacement",
        actual_stdout: b"LAbCde\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "sed.lowercase_next_replacement",
        actual_stdout: b"lAbCde\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "sed.case_conversion_end",
        actual_stdout: b"UaEbCde\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "sed.chained_substitution",
        actual_stdout: b"b\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "awk.fnr_single_input",
        actual_stdout: b"\n\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "awk.fs_multichar_regex",
        actual_stdout: b"1 a,,b:c  \n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "awk.numeric_string_comparison",
        actual_stdout: b"1 0\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "awk.length_record",
        actual_stdout: b"\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "awk.index_unicode",
        actual_stdout: b"0\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "awk.printf_dynamic_width",
        actual_stdout: b"",
        actual_success: false,
        stderr_contains: "unsupported printf conversion '%*'",
    },
    KnownFailure {
        id: "awk.convfmt",
        actual_stdout: b"0.333333\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "awk.ofmt",
        actual_stdout: b"0.333333\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "awk.large_number_default_format",
        actual_stdout: b"100000000000000000000\n",
        actual_success: true,
        stderr_contains: "",
    },
    KnownFailure {
        id: "awk.regex_match_operator",
        actual_stdout: b"",
        actual_success: false,
        stderr_contains: "unexpected character '~'",
    },
    KnownFailure {
        id: "awk.gsub_builtin",
        actual_stdout: b"",
        actual_success: false,
        stderr_contains: "unknown function 'gsub'",
    },
    KnownFailure {
        id: "awk.user_function",
        actual_stdout: b"",
        actual_success: false,
        stderr_contains: "unknown function 'twice'",
    },
];

fn cases() -> impl Iterator<Item = &'static Case> {
    [GREP_CASES, RIPGREP_CASES, SED_CASES, AWK_CASES]
        .into_iter()
        .flatten()
}

fn known(id: &str) -> Option<&'static KnownFailure> {
    KNOWN_FAILURES.iter().find(|failure| failure.id == id)
}

fn run(case: &Case) -> Output {
    let mut child = Command::new(env!("CARGO_BIN_EXE_se"))
        .arg(case.program)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap_or_else(|error| panic!("{}: failed to spawn se: {error}", case.id));
    child
        .stdin
        .take()
        .expect("piped stdin")
        .write_all(case.input)
        .unwrap_or_else(|error| panic!("{}: failed to write stdin: {error}", case.id));
    child
        .wait_with_output()
        .unwrap_or_else(|error| panic!("{}: failed to wait for se: {error}", case.id))
}

fn desired_mismatch(case: &Case, output: &Output) -> Option<String> {
    let success = output.status.success();
    if success == case.expected_success
        && (!case.expected_success || output.stdout == case.expected_stdout)
        && (!case.expected_success || output.stderr.is_empty())
    {
        return None;
    }
    Some(format!(
        "{} [{:?}; {}]\n  program: {:?}\n  input: {}\n  expected: success={}, stdout={}\n  actual: success={}, code={:?}, stdout={}, stderr={}",
        case.id,
        case.family,
        case.origin,
        case.program,
        bytes(case.input),
        case.expected_success,
        bytes(case.expected_stdout),
        success,
        output.status.code(),
        bytes(&output.stdout),
        bytes(&output.stderr),
    ))
}

fn bytes(value: &[u8]) -> String {
    if let Ok(text) = std::str::from_utf8(value) {
        format!("{text:?}")
    } else {
        let hex = value
            .iter()
            .map(|byte| format!("{byte:02x}"))
            .collect::<Vec<_>>()
            .join(" ");
        format!("<non-UTF-8: {hex}>")
    }
}

#[test]
fn static_compatibility_corpus() {
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for case in cases().filter(|case| known(case.id).is_none()) {
        checked += 1;
        let output = run(case);
        if let Some(mismatch) = desired_mismatch(case, &output) {
            failures.push(mismatch);
        }
    }
    assert!(
        failures.is_empty(),
        "{}/{} undocumented compatibility cases failed:\n\n{}",
        failures.len(),
        checked,
        failures.join("\n\n"),
    );
}

#[test]
fn documented_known_failures_are_stable() {
    let mut failures = Vec::new();
    for expected in KNOWN_FAILURES {
        let Some(case) = cases().find(|case| case.id == expected.id) else {
            failures.push(format!("{}: no corresponding static Case", expected.id));
            continue;
        };
        let output = run(case);
        let actual_success = output.status.success();
        let actual_stderr = String::from_utf8_lossy(&output.stderr);
        if actual_success != expected.actual_success
            || output.stdout != expected.actual_stdout
            || !actual_stderr.contains(expected.stderr_contains)
        {
            failures.push(format!(
                "{} changed\n  pinned actual: success={}, stdout={}, stderr contains {:?}\n  new actual: success={}, code={:?}, stdout={}, stderr={}",
                expected.id,
                expected.actual_success,
                bytes(expected.actual_stdout),
                expected.stderr_contains,
                actual_success,
                output.status.code(),
                bytes(&output.stdout),
                bytes(&output.stderr),
            ));
        }
        if desired_mismatch(case, &output).is_none() {
            failures.push(format!(
                "{} now passes its desired compatibility expectation; remove it from KNOWN_FAILURES and the Markdown ledger",
                expected.id
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} known-failure baselines changed:\n\n{}",
        failures.len(),
        failures.join("\n\n"),
    );
}

// Run this ignored test explicitly for the intentional red-suite audit.
// A non-zero result is expected until every ledger entry is fixed.
#[test]
#[ignore = "intentional red suite; see docs/compatibility.md"]
fn full_compatibility_audit() {
    let mut failures = Vec::new();
    let mut checked = 0usize;
    for case in cases() {
        checked += 1;
        let output = run(case);
        if let Some(mismatch) = desired_mismatch(case, &output) {
            failures.push(mismatch);
        }
    }
    assert!(
        failures.is_empty(),
        "{}/{} compatibility cases failed:\n\n{}",
        failures.len(),
        checked,
        failures.join("\n\n"),
    );
}
